export const TEAM_NAME_BY_FIFA_CODE: Record<string, string> = {
  ARG: 'Argentina',
  AUS: 'Austrália',
  AUT: 'Áustria',
  BEL: 'Bélgica',
  BRA: 'Brasil',
  CAN: 'Canadá',
  COL: 'Colômbia',
  CRC: 'Costa Rica',
  CRO: 'Croácia',
  CUR: 'Curaçao',
  CUW: 'Curaçao',
  DEN: 'Dinamarca',
  ECU: 'Equador',
  EGY: 'Egito',
  ENG: 'Inglaterra',
  ESP: 'Espanha',
  FRA: 'França',
  GER: 'Alemanha',
  GHA: 'Gana',
  IRN: 'Irã',
  ITA: 'Itália',
  JPN: 'Japão',
  KOR: 'Coreia do Sul',
  MAR: 'Marrocos',
  MEX: 'México',
  NED: 'Holanda',
  NGA: 'Nigéria',
  NOR: 'Noruega',
  NZL: 'Nova Zelândia',
  PAN: 'Panamá',
  PAR: 'Paraguai',
  PER: 'Peru',
  POL: 'Polônia',
  POR: 'Portugal',
  QAT: 'Catar',
  RSA: 'África do Sul',
  SEN: 'Senegal',
  SRB: 'Sérvia',
  SUI: 'Suíça',
  SWE: 'Suécia',
  TUN: 'Tunísia',
  TUR: 'Turquia',
  UKR: 'Ucrânia',
  URU: 'Uruguai',
  USA: 'Estados Unidos',
  VEN: 'Venezuela',
  WAL: 'País de Gales',
}

export function localizeTeamName(fifaCode: string | null | undefined, fallbackName: string): string {
  if (!fifaCode) {
    return fallbackName
  }

  return TEAM_NAME_BY_FIFA_CODE[fifaCode] ?? fallbackName
}
