import { OUTRIGHT_MARKET_CODES, type OutrightMarketCode } from './catalog.js'

export const PLAYER_MARKET_OPTIONS: Partial<Record<OutrightMarketCode, string[]>> = {
  [OUTRIGHT_MARKET_CODES.TOP_SCORER]: [
    'Kylian Mbappe',
    'Erling Haaland',
    'Vinicius Junior',
    'Harry Kane',
    'Lautaro Martinez',
    'Julian Alvarez',
    'Jude Bellingham',
    'Florian Wirtz',
    'Lamine Yamal',
    'Endrick',
    'Cole Palmer',
    'Phil Foden',
    'Rasmus Hojlund',
    'Alexander Isak',
    'Victor Osimhen',
    'Santiago Gimenez',
    'Omar Marmoush',
    'Joao Pedro',
    'Benjamin Sesko',
    'Serhou Guirassy',
  ],
  [OUTRIGHT_MARKET_CODES.GOLDEN_BALL]: [
    'Kylian Mbappe',
    'Vinicius Junior',
    'Jude Bellingham',
    'Rodri',
    'Pedri',
    'Lamine Yamal',
    'Jamal Musiala',
    'Florian Wirtz',
    'Lautaro Martinez',
    'Julian Alvarez',
    'Phil Foden',
    'Cole Palmer',
    'Martin Odegaard',
    'Federico Valverde',
    'Bruno Fernandes',
    'Bernardo Silva',
    'Khvicha Kvaratskhelia',
    'Rodrygo',
    'Declan Rice',
    'Bukayo Saka',
  ],
  [OUTRIGHT_MARKET_CODES.REVELATION]: [
    'Lamine Yamal',
    'Endrick',
    'Warren Zaire-Emery',
    'Joao Neves',
    'Arda Guler',
    'Pau Cubarsi',
    'Kobbie Mainoo',
    'Estevao',
    'Savinho',
    'Benjamin Sesko',
    'Desire Doue',
    'Kenan Yildiz',
    'Archie Gray',
    'Jorrel Hato',
    'Assane Diao',
    'Can Uzun',
    'Mathys Tel',
    'Ethan Nwaneri',
    'Claudio Echeverri',
    'Franco Mastantuono',
  ],
}
