import { OUTRIGHT_MARKET_CODES, type OutrightMarketCode } from './catalog.js'
import type { OutrightPlayerSourceTier } from './player-option-types.js'

export interface PlayerMarketOption {
  label: string
  teamLabel: string
  sourceTier: OutrightPlayerSourceTier
  isFeatured: boolean
}

function player(
  name: string,
  teamLabel: string,
  sourceTier: OutrightPlayerSourceTier,
  isFeatured = false,
): PlayerMarketOption {
  return {
    label: `${name} - ${teamLabel}`,
    teamLabel,
    sourceTier,
    isFeatured,
  }
}

export const PLAYER_MARKET_OPTIONS: Partial<Record<OutrightMarketCode, PlayerMarketOption[]>> = {
  [OUTRIGHT_MARKET_CODES.TOP_SCORER]: [
    player('Kylian Mbappe', 'Franca', 'OFFICIAL', true),
    player('Vinicius Junior', 'Brasil', 'OFFICIAL', true),
    player('Harry Kane', 'Inglaterra', 'LIKELY', true),
    player('Lautaro Martinez', 'Argentina', 'LIKELY', true),
    player('Lamine Yamal', 'Espanha', 'LIKELY', true),
    player('Erling Haaland', 'Noruega', 'LIKELY'),
    player('Julian Alvarez', 'Argentina', 'LIKELY'),
    player('Marcus Thuram', 'Franca', 'OFFICIAL'),
    player('Ousmane Dembele', 'Franca', 'OFFICIAL'),
    player('Bradley Barcola', 'Franca', 'OFFICIAL'),
    player('Randal Kolo Muani', 'Franca', 'OFFICIAL'),
    player('Michael Olise', 'Franca', 'OFFICIAL'),
    player('Rodrygo', 'Brasil', 'OFFICIAL'),
    player('Raphinha', 'Brasil', 'OFFICIAL'),
    player('Pedro', 'Brasil', 'OFFICIAL'),
    player('Endrick', 'Brasil', 'OFFICIAL'),
    player('Savinho', 'Brasil', 'OFFICIAL'),
    player('Richarlison', 'Brasil', 'OFFICIAL'),
    player('Arda Guler', 'Turquia', 'PRELIMINARY'),
    player('Kenan Yildiz', 'Turquia', 'PRELIMINARY'),
    player('Kerem Akturkoglu', 'Turquia', 'PRELIMINARY'),
    player('Baris Alper Yilmaz', 'Turquia', 'PRELIMINARY'),
    player('Akram Afif', 'Catar', 'PRELIMINARY'),
    player('Almoez Ali', 'Catar', 'PRELIMINARY'),
    player('Aymen Hussein', 'Iraque', 'PRELIMINARY'),
    player('Mohanad Ali', 'Iraque', 'PRELIMINARY'),
    player('Zeki Amdouni', 'Suica', 'OFFICIAL'),
    player('Breel Embolo', 'Suica', 'OFFICIAL'),
    player('Joao Pedro', 'Brasil', 'OFFICIAL'),
    player('Alexander Isak', 'Suecia', 'LIKELY'),
    player('Victor Osimhen', 'Nigeria', 'LIKELY'),
    player('Santiago Gimenez', 'Mexico', 'LIKELY'),
    player('Serhou Guirassy', 'Guine', 'LIKELY'),
    player('Omar Marmoush', 'Egito', 'LIKELY'),
    player('Jonathan David', 'Canada', 'LIKELY'),
  ],
  [OUTRIGHT_MARKET_CODES.GOLDEN_BALL]: [
    player('Kylian Mbappe', 'Franca', 'OFFICIAL', true),
    player('Vinicius Junior', 'Brasil', 'OFFICIAL', true),
    player('Jude Bellingham', 'Inglaterra', 'LIKELY', true),
    player('Rodri', 'Espanha', 'LIKELY', true),
    player('Jamal Musiala', 'Alemanha', 'LIKELY', true),
    player('Lamine Yamal', 'Espanha', 'LIKELY'),
    player('Florian Wirtz', 'Alemanha', 'LIKELY'),
    player('Pedri', 'Espanha', 'LIKELY'),
    player('Rodrygo', 'Brasil', 'OFFICIAL'),
    player('Raphinha', 'Brasil', 'OFFICIAL'),
    player('Bruno Guimaraes', 'Brasil', 'OFFICIAL'),
    player('Casemiro', 'Brasil', 'OFFICIAL'),
    player('Eduardo Camavinga', 'Franca', 'OFFICIAL'),
    player('Aurelien Tchouameni', 'Franca', 'OFFICIAL'),
    player('Adrien Rabiot', 'Franca', 'OFFICIAL'),
    player('Michael Olise', 'Franca', 'OFFICIAL'),
    player('Federico Valverde', 'Uruguai', 'LIKELY'),
    player('Bernardo Silva', 'Portugal', 'LIKELY'),
    player('Bruno Fernandes', 'Portugal', 'LIKELY'),
    player('Bukayo Saka', 'Inglaterra', 'LIKELY'),
    player('Declan Rice', 'Inglaterra', 'LIKELY'),
    player('Martin Odegaard', 'Noruega', 'LIKELY'),
    player('Lautaro Martinez', 'Argentina', 'LIKELY'),
    player('Julian Alvarez', 'Argentina', 'LIKELY'),
    player('Arda Guler', 'Turquia', 'PRELIMINARY'),
    player('Kenan Yildiz', 'Turquia', 'PRELIMINARY'),
    player('Granit Xhaka', 'Suica', 'OFFICIAL'),
    player('Xherdan Shaqiri', 'Suica', 'OFFICIAL'),
    player('Franck Kessie', 'Costa do Marfim', 'OFFICIAL'),
    player('Simon Adingra', 'Costa do Marfim', 'OFFICIAL'),
    player('Sebastien Haller', 'Costa do Marfim', 'OFFICIAL'),
    player('Akram Afif', 'Catar', 'PRELIMINARY'),
    player('Aymen Hussein', 'Iraque', 'PRELIMINARY'),
    player('Gervane Kastaneer', 'Curacao', 'OFFICIAL'),
    player('Jeremy Antonisse', 'Curacao', 'OFFICIAL'),
  ],
  [OUTRIGHT_MARKET_CODES.REVELATION]: [
    player('Lamine Yamal', 'Espanha', 'LIKELY', true),
    player('Endrick', 'Brasil', 'OFFICIAL', true),
    player('Estevao', 'Brasil', 'OFFICIAL', true),
    player('Kenan Yildiz', 'Turquia', 'PRELIMINARY', true),
    player('Pau Cubarsi', 'Espanha', 'LIKELY', true),
    player('Warren Zaire-Emery', 'Franca', 'OFFICIAL'),
    player('Desire Doue', 'Franca', 'OFFICIAL'),
    player('Senny Mayulu', 'Franca', 'OFFICIAL'),
    player('Wesley', 'Brasil', 'OFFICIAL'),
    player('Andrey Santos', 'Brasil', 'OFFICIAL'),
    player('Joao Gomes', 'Brasil', 'OFFICIAL'),
    player('Arda Guler', 'Turquia', 'PRELIMINARY'),
    player('Can Uzun', 'Turquia', 'PRELIMINARY'),
    player('Semih Kilicsoy', 'Turquia', 'PRELIMINARY'),
    player('Johan Manzambi', 'Suica', 'OFFICIAL'),
    player('Mouhamadou Diarra', 'Costa do Marfim', 'OFFICIAL'),
    player('Yan Diomande', 'Costa do Marfim', 'OFFICIAL'),
    player('Ali Jasim', 'Iraque', 'PRELIMINARY'),
    player('Lucas Stassin', 'Belgica', 'LIKELY'),
    player('Kobbie Mainoo', 'Inglaterra', 'LIKELY'),
    player('Archie Gray', 'Inglaterra', 'LIKELY'),
    player('Mathys Tel', 'Franca', 'LIKELY'),
    player('Warren Madrigal', 'Costa Rica', 'LIKELY'),
    player('Franco Mastantuono', 'Argentina', 'LIKELY'),
    player('Claudio Echeverri', 'Argentina', 'LIKELY'),
    player('Yaser Asprilla', 'Colombia', 'LIKELY'),
    player('Savinho', 'Brasil', 'OFFICIAL'),
    player('Jhon Duran', 'Colombia', 'LIKELY'),
    player('Oscar Gloukh', 'Israel', 'LIKELY'),
    player('Bilal El Khannouss', 'Marrocos', 'LIKELY'),
  ],
}
